### ISSUE TITLE
Add package management tools to lock package versions

### ISSUE THREAD

**Issue by Darkborderman** [pycontw/pycon-regbot#5]
Currently the repository does not have management tools to control/maintain versions.  No package version control may lead to conflict/confusion when installing on different instances.

**Comment by Darkborderman** [comment]
Hello @jordanSu may I pick up this issue?

**Comment by jordanSu** [comment]
@Darkborderman Yap sure, feel free to take it!

**Comment by jordanSu** [comment]
Fix in #6 , close now.
